### ISSUE TITLE
Installer runs successfully, but still can't view DRM protected content

### ISSUE THREAD

**Issue by enewbury** [AsahiLinux/widevine-installer#8]
I'm running Fedora Linux Asahi Remix 39 on an M1 Max chip and ran the installer seemingly successfully, but DRM protected content like spotify is still not playable in firefox or brave.

Note, the installer showed this output
```
Good news! This CDM version supports your page size, so we didn't have
to weaken memory permissions. Rejoice!
```
Based on the blog post explaining this, I didn't expect this to be the case, unless something has recently changed, so I thought I would mention it in case it's relevant.

**Comment by enewbury** [comment]
Yes, and full computer restart just to be sure.

**Comment by looooo** [comment]
same problem here with asahi ubuntu.

**Comment by lokxii** [comment]
I can play Spotify but not Netflix...

**Comment by m3957** [comment]
Me, also, I cannot get Spotify working on Firefox. Weirdly enough, Chromium works. On [this website](https://bitmovin.com/demos/drm), it says I'm using Firefox using no DR.

**Comment by enewbury** [comment]
Just tried this again after the updates 2 weeks ago and it all works now! Thanks for the fix!

**Comment by lokxii** [comment]
It still doesn't work on my machine. I can't watch netflix after updating widevine installer and rerunning it

**Comment by Thinkseal** [comment]
I believe I am having this issue as well on firefox but I have not tested on chromium

**Comment by enewbury** [comment]
For Netflix I still had to spoof the useragent to be chrome on chromeOS. Just wanted to double check you've got that setup.

**Comment by 38github** [comment]
Just want to share that I got it working on an RPi5 under Void Linux (glibc) using Firefox from the Void Linux repository. Chromium didn't want to play Prime video but I have to look at the chrome flags to see if I have set myself up for failure. 

Thank you for doing this!
